#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.15f1_13f5a1bf9ca1"
#define UNITY_VERSION_FULL_NICE "2018.4.15f1 (13f5a1bf9ca1)"
#define UNITY_VERSION_BLD 1308065
#define UNITY_VERSION_DATE 1576757491
#define UNITY_VERSION_WIN "2018.4.15.1308065"
#define UNITY_VERSION_BRANCH "2018.4/release"
